---
title: "Documents Quarto"
subtitle: "Les types de sorties existants"
author: "A. Mercadié et C. Regouby"
date: today
institute: "MIAT INRAE - PFDC & Airbus"
format:
  revealjs: 
    slide-number: true
    theme: solarized
    incremental: true
    slide-level: 3
    logo: images/logoRuserToulouse.svg
    smaller: true
    reference-location: document
---

## Liste

-   Faire une petite liste de ce qui est dispo en Quarto avec Rstudio IDE
-   Comparaison avec les possibilités en Rmarkdown/Knitr so far
-   Pour les sorties les plus connues, donner les petits plus (ou les moins si il y a)
-   Documenter ça avec plein de ressources

## Notebook

Déjà fait tout à l'heure, mais si détails supplémentaires à donner, le faire ici.

-   Mettre le lien des pages R d'aide de fonctions
-   Cacher/Montrer le code (déjà dispo dans Rmarkdown je crois)
-   Mettre des figures à côté (et non plus juste en dessous) du code
-   
-   Les trucs un peu gadget mais quand même cool: 
    * pouvoir éditer le notebook (HTML) en mode clair ou sombre
    
::: notes
Tentative pour les slides mais échec jusque-là..
:::
    

## Présentations

-   Reveal.js
-   Beamer
-   Même possible d'exporter en .ppt $\Rightarrow$ au revoir les captures écran pour intégrer les graphiques et tableaux depuis R dans les présentations!

## Présentations: les petits plus

-   Le truc vu dans la keynote pour entourer des choses sur la slide ou ouvrir un tableau, sans rien d'autre que la présentation HTML (à tester avant)
-   L'extension pointeur

## Blogs, sites webs

Beaucoup moins mon domaine, donc quelques ressources et notions de bases.

## Articles, books

Pas mon domaine d'expertise non plus mais se renseigner rapidement.
